version: "3"

services:
  app:
    image: itzg/minecraft-server:multiarch-latest
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - "mc:/data"
    environment:
      OVERRIDE_SERVER_PROPERTIES: 'true'
      EULA: "TRUE"
    env_file:
      - .env

volumes:
  mc:
