POST {{host}}/hello
Content-Type: application/json;charset=UTF-8

{
  "target": "{{target}}",
  "message": "awd"
}

> {% client.test("status ok with result", function() {
  client.assert(response.status === 200);
}) %}

###

