import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useForm, Controller } from "react-hook-form";
import { useState } from "react";

interface IMessageFormDto {
  target: string;
  message: string;
}

export default function Home() {
  const [result, setResult] = useState("");
  const { control, handleSubmit } = useForm<IMessageFormDto>({
    defaultValues: {
      message: "",
      target: "",
    },
  });

  const send = async (dto: IMessageFormDto) => {
    const response = await fetch("/api/hello", {
      method: "POST",
      body: JSON.stringify(dto),
    });
    const text = await response.text();

    setResult(text);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={handleSubmit(send)}>
          <Controller
            control={control}
            rules={{ required: true }}
            name={"target"}
            render={({ field }) => (
              <>
                <label htmlFor={field.name}>{field.name}:</label>
                <input
                  id={field.name}
                  type="text"
                  name={field.name}
                  value={field.value}
                  onChange={(e) => field.onChange(e.target.value)}
                />
              </>
            )}
          />
          <Controller
            control={control}
            rules={{ required: true }}
            name={"message"}
            render={({ field }) => (
              <>
                <label htmlFor={field.name}>{field.name}:</label>
                <input
                  id={field.name}
                  type="text"
                  name={field.name}
                  value={field.value}
                  onChange={(e) => field.onChange(e.target.value)}
                />
              </>
            )}
          />
          <button type="submit">send</button>
        </form>
        {!!result && <p>Result: {result}</p>}
      </main>
    </div>
  );
}
