import Head from "next/head";
import { Controller, useForm } from "react-hook-form";
import type { IMessageDto } from "../src/client";
import { useMessage } from "../src/client";

export default function Home() {
  const { control, handleSubmit } = useForm<IMessageDto>({
    defaultValues: {
      message: "",
      target: "",
    },
  });
  const { result, sendMessage } = useMessage();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form onSubmit={handleSubmit(sendMessage)}>
        <Controller
          control={control}
          rules={{ required: true }}
          name={"target"}
          render={({ field }) => (
            <>
              <label htmlFor={field.name}>{field.name}:</label>
              <input
                id={field.name}
                type="text"
                name={field.name}
                value={field.value}
                onChange={(e) => field.onChange(e.target.value)}
              />
            </>
          )}
        />
        <Controller
          control={control}
          rules={{ required: true }}
          name={"message"}
          render={({ field }) => (
            <>
              <label htmlFor={field.name}>{field.name}:</label>
              <input
                id={field.name}
                type="text"
                name={field.name}
                value={field.value}
                onChange={(e) => field.onChange(e.target.value)}
              />
            </>
          )}
        />
        <button type="submit">send</button>
      </form>
      {!!result && <p>Result: {result}</p>}
    </>
  );
}
